### PR TITLE
Use properties of task to track the task running status.

### PR DESCRIPTION
**Pull request by shinima**
Implementation for  #1468  Option-3

### CODE REVIEW

**Comment by Andarist** [comment]
Could u rebase this? CI fix got merged onto master today.

**Comment by shinima** [comment]
Rebased.  @Andarist

**Comment by shinima** [comment]
@restrry  I have changed  `mainTask.isRunning`  to `mainTask._isRunning`. How do you think?

**Comment by Andarist** [comment]
Not sure if this rename is needed, mainTask is internal anyway. I'm also not strongly opposed to it either. Whatever u both work out regarding this one.

**Comment by restrry** [comment]
regarding naming - my confusion was about having booleans with the same semantic `task._isRunning` and `mainTask.isRunning` , but `task.isRunning()` is a method at the same time.
we can leave everything as is, but I'd prefer to have any kind of unification for naming :)

**Pull request merged**
