### PR TITLE
internal: Rename `iterator._XXX` to more explicit names.

### PR DESCRIPTION
**Pull request by shinima**
From #1399

- Rename `_isRunning` to `_isTaskRunning` (same for `_isCancelled` and `_isAborted`)
- Rename `_result` to `_taskResult`; rename `_error` to `_taskError`.

### CODE REVIEW

**Comment by Andarist** [comment]
This looks good, I'm only thinking that maybe keeping those on `iterator` is somewhat leaky. It feels wrong to mutate it. Maybe we could try to keep those flags on the task's instance instead? It's our custom object and makes more sense to keep it there. WDYT?

**Comment by shinima** [comment]
I came up with several options:

### Option-1
Like in this PR now, rename `_isRunning` to `_isTaskRunning` (same for `_isCancelled` and `_isAborted`)
rename `_result` to `_taskResult`; rename _error to `_taskError`.

* pros: make the names more explicit.
> cons: keeping those on iterator is somewhat leaky

### Option-2
Convert `task.isRunning / task.isCancelled ...` from methods to properties, and use these properties to track the running status of the task. I have tried this option in my [little-saga](https://github.com/shinima/little-saga/blob/master/src/core/Task.js#L4-L9), and it works pretty well (passed almost all of redux-saga test cases).
* pros: It is simple, intuitive and explicit.
* cons: It introduces breaking changes since that the [API doc](https://github.com/redux-saga/redux-saga/tree/master/docs/api#task) already says `task.isRunning ...` are methods.

### Option-3

Like in #1404 , using properties and methods at the same time. Using properties `task._isRunning / task_.isCancelled ... ` to track running status, while still provides `task.isRunning() / task.isCancelled()`.

* pros: get rid of `iterator._xxx`
* cons: having methods and properties at the same time seems unnecessary

### My opinion
I think `Task.isRunning() / Task.isCancelled()...` are not popular APIs and we are toward version 1.0, so option-2 is the best option. How do you think ?

**Comment by Andarist** [comment]
I'm not against introducing breaking changes for this, so option 2 is fine. It has additional drawback though - properties might imply that they can be changed and those should really be read-only outside of redux-saga code. So I'm kinda leaning towards option 3 at the moment.

> I have tried this option in my little-saga

That is really cool! What are your goals for this project? You might be also interested in [this project](https://github.com/briancavalier/forgefx).

**Comment by Andarist** [comment]
@restrry WDYT about this?

**Comment by shinima** [comment]
little-saga is a slim version of redux-saga. I made some breaking change (including using `task.isRunning / task.isCancelled ...` to track running status) to keep little-saga as simple as possible. And I wrote an article in Chinese to help people understand the internals of redux-saga/little-saga.

> properties might imply that they can be changed and those should really be read-only outside of redux-saga code

We can document that `task.isRunning / task.isCancelled` is read-only and add `readonly` modifier in typescript declaration file. On the other hand, I think most users will use join/cancel/cancelled effects 
rather than using these APIs to inspect the running status. These APIs could be think as advanced APIs and maybe we can trust these advanced APIs users 😆 .

@Andarist If you think option-2 is okay, I am glad to make a PR. Or if you think option-3 is better, I can reopen #1404.

**Comment by restrry** [comment]
👍 for option-3.
pros: no breaking changes. and if we need add some addition logic (in future) for getting/setting those flags, we already have isolation from external api.
the only remark - does it make sense to rename mainTask.isRunning -> `mainTask._isRunning` to have  make them more consistent?

**Comment by shinima** [comment]
So let's pick option-3.   `mainTask._isRunning` is very reasonable though mainTask is private in `proc()`. I will add commits in #1475.

**Pull request closed without merging**
