### PR TITLE
Update TypeScript definitions

### PR DESCRIPTION
**Pull request by aikoven**
**BREAKING CHANGE**
This PR can potentially break builds for TS users.

* Stronger typings for `call`, `fork` etc effects. Passed argument types are now checked correctly.
* Add tests.
* Add missing and remove deprecated APIs.
* Export effect descriptor types to aid testing.
* Includes some of not yet merged APIs: ~~https://github.com/redux-saga/redux-saga/pull/733~~, https://github.com/redux-saga/redux-saga/pull/739
* Helpers (`takeEvery`, `takeLatest`, `throttle`) now accept up to 6 arguments. `...rest` arguments removed for the sake of correctly checking last `action` argument. `cps` effect creator accepts up to 4 arguments.

### CODE REVIEW

**Comment by aikoven** [comment]
Resolves https://github.com/redux-saga/redux-saga/issues/608 and https://github.com/redux-saga/redux-saga/issues/619.

**Comment by Andarist** [comment]
> remove deprecated APIs

I think they should be kept while deprecated and dropped accordingly when the features are removed from the core

> Helpers (takeEvery, takeLatest, throttle) now accept up to 6 arguments. ...rest arguments removed for the sake of correctly checking last action argument. cps effect creator accepts up to 4 arguments.

wont it be limiting? aint possible making those of completely variadic length?

**Comment by aikoven** [comment]
> wont it be limiting? aint possible making those of completely variadic length?

Latest TS only supports vararg at the end of arguments list, so it's impossible to strongly annotate `(...args, action)`. I think I'll return the `...rest` version, but `action` argument won't be type-checked.

**Comment by CarsonF** [comment]
@aikoven Can you add `emitter` to the `Monitor` interface?

**Comment by nbostrom** [comment]
These typing doesn't actually allow the iterator to use `delay` since it returns a Promise in place of an Effect. I think that we need to update the SagaIterator definition to something like:
```
export type SagaIterator = IterableIterator<Effect|Effect[]|Promise<any>>;
```
Or update the Effect def if redux-saga counts Promises as Effecs.
I'm not very good at typescript yet, so there's probably a better way. ;)

**Comment by aikoven** [comment]
@nbostrom IMO `yield`ing promises is an anti-pattern, since it means you create a side-effect in the generator itself instead of saga runtime. You can use `yield call(delay, 50)` instead, which is pure.

**Comment by nbostrom** [comment]
@aikoven Oh, I see. That makes a lot of sense. Thanks!

**Comment by Andarist** [comment]
@aikoven whats the status of the PR? do you know what things does it include? should I cross check against what might be missing and what potentially could be updated? or are you on master's toes? ;)

would like to proceed with this PR as im preparing a new release (no rush though!), if I can help in any way, just let me know

**Comment by aikoven** [comment]
@Andarist There are a couple things that should be done:
1. [`yield cancel(...tasks)`](https://github.com/redux-saga/redux-saga/pull/800). I'm confused about whether it is in `master` already.
2. `onError` option for `runSaga`
3. Possibly a solution for https://github.com/redux-saga/redux-saga/pull/770

**Comment by aikoven** [comment]
Updated the PR. Added some missing APIs and loosened restriction on generators passed to `SagaMiddleware.run` as well as iterators passed to `runSaga`. Strict type-check of `yield`ed values is still possible by annotating return types of generators with `SagaIterator`.

**Comment by Andarist** [comment]
Thanks for updating the PR! Im trying to push v0.15 forward and I think I wont release anything in between. Some things ere not yet merged in, but I think their typings could be provided in this PR, so we do not have to come back to the matter latter:

- `runSaga` refactor - basically just 1. args reordering (store interface geting in there first) 2. it accepting a generator instead of an iterator instance 3. variadic args at the end to be passed into the generator internally. That means that `sagaMiddleware.run` becomes just partially applied `runSaga` - dont know if that helps you to dedup something
- self cancellation - `cancel(task)` and `cancel()` becomes valid, but not `cancel(undefined)`!
- `all` effect - just an explicit alternative for `yield [...effects]`
- context features from #735 - so `getContext`, `setContext` effects and things like `sagaMiddleware.setContext` and `{ options: { context } }` passed in upon creation - although maybe i would hold with that until the PR is more stabilized. There are some unanswered comments in the added code, maybe you could look into them?

**Comment by aikoven** [comment]
Do you expect all of these to be merged for `v0.15`? Otherwise I could just make another PR.

**Comment by Andarist** [comment]
Yeah, I would like to include all of them in v0.15

**Comment by Andarist** [comment]
cc @aikoven #823

**Comment by aikoven** [comment]
- [ ] New `runSaga` signature
- [ ] Self cancellation via `yield cancel()`
- [ ] `all` effect
- [ ] Context feature

**Comment by aikoven** [comment]
- [ ] Support for passing method names to `call` etc. https://github.com/redux-saga/redux-saga/pull/826

**Comment by dcolthorp** [comment]
+💯 Many of the current definitions are close to useless, as they provide no safety.

Any news as to whether this will be merged and/or released? It would be nice to at least pin to a commit in the `redux-saga` instead of a fork.

**Comment by Andarist** [comment]
@dcolthorp 
Yes, this is certianly going to be merged. Cannot give exact estimate though, trying to push things forward as quick as I can.

Is this PR solving ur problem?

**Comment by dcolthorp** [comment]
@Andarist Yeah, they're exactly what I was hoping for. One of the main reasons to use TypeScript to begin with is safety, and the currently released type definitions are useless there, because any invalid arguments to e.g. `call` fall back on an alternate definition that completely gives up type safety.

The currently released type definitions are problematic enough that I was questioning the viability of using sagas in my TypeScript project at all until I found this PR. I suspect getting this merged would be of high priority to anyone using sagas in typescript.

**Comment by Andarist** [comment]
I'll try to review what needs to be done, so this can get merged in.

**Comment by Andarist** [comment]
Merged in, preparing a release. Stay tuned. ;)

**Comment by dcolthorp** [comment]
Excellent, thank you @Andarist and @aikoven for your work!

**Comment by Andarist** [comment]
@aikoven needs some loud 👏 👏 here, ive just merged it in ;)

**Pull request merged**
