### PR TITLE
Enhancing onError callback for createSagaMiddleware

### PR DESCRIPTION
**Pull request by al-zah**
Allow for `onError` callback to take an additional param with getState function.

This would allow to retrieve snapshot of the last state before error did happen and possibly send it to error tracking service such as sentry.io.

### CODE REVIEW

**Comment by Andarist** [comment]
Is it even possible to send big states to sentry?

**Comment by slorber** [comment]
Hi,

Funny as I'm also working on getSentry.

I think it accept big JSON states yes.

It would only be for conveniency because you can easily call store.getState() directly in your error listener, I'm not sure it's worth changing the signature of onError just for this usecase

**Comment by al-zah** [comment]
@Andarist Thats what sentry is recommends when using redux: https://blog.sentry.io/2016/08/24/redux-middleware-error-logging.html

@slorber You right, it's better to call getState directly, going to close this PR, sorry for wasted time :sweat_smile:

**Comment by Andarist** [comment]
@al-zah still its probably preferable to you to use also `onError` handler in the `redux-saga` as not all exceptions can be caught by this sentry middleware.

**Pull request closed without merging**
