### PR TITLE
Snippet

### PR DESCRIPTION
**Pull request by LordMoMA**
| Q                       | A                                         |
| ----------------------- | ---------------------------------------------------------------------- |
| Fixed Issues?           | `Fixes #1, Fixes #2`  |
| Patch: Bug Fix?         |                                                                        |
| Major: Breaking Change? |                                                                        |
| Minor: New Feature?     |                                                                        |
| Tests Added + Pass?     | Yes                                                                    |
| Any Dependency Changes? |                                                                        |

To whom it may concern,

I have add a new snippet 4 besides the snippet 3 in the Example Usage from the main page. If we can improve the docs with the optimised version, redux-saga could be more user-friendly and cause less confusion for future developers.

You can ignore the configureStore branch and merge this branch please. 

If the code is no problem, and I would be happy to add it along the the rest createStore docs gradually.

Cheers,
David

### CODE REVIEW

**Comment by neurosnap** [comment]
Thanks for this PR!  It looks pretty good to me.  I'd like to take a stab at reviewing the docs and making some bigger changes to modernize our thinking about `redux-saga`

**Comment by LordMoMA** [comment]
You’re welcome. I cannot wait to see a mordernized
Redux-saga now ;)

**Review by neurosnap — APPROVED** [review]

**Comment by neurosnap** [comment]
Circling back to this, can you resolve the conflicts and then I'll merge?  Thanks!

**Comment by LordMoMA** [comment]
Conflicts resolved, cheers ;)

**Pull request merged**
