### PR TITLE
Add link to redux-saga-compose

### PR DESCRIPTION
**Pull request by sdd**

### CODE REVIEW

**Comment by Andarist** [comment]
Nice work! Ive commented on the few things in your repo.

**Comment by sdd** [comment]
Thanks! Appreciate the feedback. I've refactored out the `for/in` and relaxed the checks so that non-generator functions can be used as middleware. Republished as 1.1.1.

**Comment by sdd** [comment]
Hi! is there anything preventing this link being merged in that I need to do?

Thanks

**Comment by Andarist** [comment]
Nope ;)

**Pull request merged**
