### PR TITLE
Modify publication script so gh-pages can be protected

### PR DESCRIPTION
**Pull request by lukePeavey**
Possible solution for #1252

I modified the publication script to use the [gh-pages](https://github.com/tschaub/gh-pages) package to deploy the documentation site. It performs the same task as the current script but doesn't force push to gh-pages. Instead, a new commit will be added each time the script is run. 

I've tested this and it seems to be working fine. The branch generated by the new script is identical to the current one. 

There is one caveat...  if the gh-pages branch is deleted from the remote repository, you need to run `gh-pages-clean` to clear the package's cache before running the publish script again. Otherwise you'll get an error. (see [this issue](https://github.com/tschaub/gh-pages/issues/17)).

This can be run manually if needed `node_modules/.bin/gh-pages-clean`

Another possibility would be to add it to the `docs:clean` script so it runs automatically before each publish. This makes the script a bit slower (because `gh-pages` will create a temporary clone of the repo each time instead of using the cached one). 

Let me know if you questions/thoughts. Im happy to provide additional info or update the PR.

### CODE REVIEW

**Comment by Andarist** [comment]
The changes are fine as far as I can tell, if they are working :)

> There is one caveat... if the gh-pages branch is deleted from the remote repository, you need to run gh-pages-clean to clear the package's cache before running the publish script again. Otherwise you'll get an error. (see this issue).

Can this become a problem? The whole point is to make the remote branch protected, so it won't be possible to delete it.

**Comment by lukePeavey** [comment]
>Can this become a problem? The whole point is to make the remote branch protected, so it won't be possible to delete it.

Its pretty much a non-issue since branch will protected. I just thought i should mention it as something to be aware of (in case you ever had to take the branch down for some reason)

**Comment by lukePeavey** [comment]
I've tested the script on [this repository](https://github.com/lukePeavey/redux-saga-clone/) if you want to take a look.

**Comment by Andarist** [comment]
Cool, gonna merge in and see how it plays out. Thanks for your hard work, I really appreciate it 👍

**Comment by lukePeavey** [comment]
Glad i was able to contribute!! I just hope it works

**Pull request merged**
