### PR TITLE
Make redux-saga fully TypeScript compatible and type safe

### PR DESCRIPTION
**Pull request by henrikra**
Redux-saga typed generator return values

| Q                        | A  |
| ------------------------ | ---  |
| Fixed Issues?            | `Fixes #1, Fixes #2`  |
| Patch: Bug Fix?          |    |
| Major: Breaking Change?  |    |
| Minor: New Feature?      |    |
| Tests Added + Pass?      | Yes |
| Any Dependency Changes?  |    |

### CODE REVIEW

**Comment by Andarist** [comment]
This isn't true though - similarly to why `call` is not type-safe currently (it just returns CallEffect). There is an ongoing discussion on how to make all effects type-safe [here](https://github.com/redux-saga/redux-saga/issues/1932). I'd like to proceed with what we've figured out there soon-ish, but I'm occupied with some other stuff right now.

If you want to help with that work I would gladly receive any help I can get. Weirdly what has to be done now is to migrate docs away from Gitbook to, preferably, gatsby. Unfortunately, Gitbook breaks current CI setup as it has a dependency on `npm` 🤦‍♂

**Comment by henrikra** [comment]
Hmm add detailed list of stuff what should be done then? :D I just want to get redux-saga to be somewhat type safe because now it is far from it :/

**Comment by Andarist** [comment]
Right now the docs migration is important - I suspect there should be some docs-like Gatsby theme that could be used to make this easy, we still want to author docs in markdown.

**Comment by neurosnap** [comment]
Greetings!  We have introduced better typings with ts3.6.  We are watching this PR closely to get even better typing support for redux-saga: https://github.com/microsoft/TypeScript/pull/47548

**Pull request closed without merging**
