### PR TITLE
fix tests on cancellable-counter example

### PR DESCRIPTION
**Pull request by GaelS**
Following #1093, I updated the tests on the cancellable-counter example.

### CODE REVIEW

**Comment by Andarist** [comment]
Cool! Let us merge [this](https://github.com/redux-saga/redux-saga/pull/1365) before merging yours though, as we'll have 100% certainty that your branch pass on CI (at the moment tests are broken due to absolute paths included in babel plugin's tests)

**Comment by Andarist** [comment]
Could u rebase ur branch against latest master?

**Comment by GaelS** [comment]
I don't know if one gets notified with a "thumbs up" on a comment but it's rebased ! :)

**Comment by Andarist** [comment]
Thanks!

> I don't know if one gets notified with a "thumbs up" 

It doesn't notify people, which sometimes is a bummer 😉

**Pull request merged**
