### PR TITLE
Implement combineLatest effect

### PR DESCRIPTION
**Pull request by NeoLegends**
In response to #1368 I'm finally coming around to implementing the effect. However, I'm a little lost on how the actual implementation within saga's proc.js has to work. Would love some assistance, currently it isn't working as intended, because `runRaceEffect` apparently cannot be used the way I want to use it.

### CODE REVIEW

**Comment by Andarist** [comment]
I would prefer this being not an actual effect, but rather a saga helper - built on top of internal `fsmIterator`. Let's keep effects (handled by proc.js) small and focused. `combineLatest` can be expressed as a composition of other effects.

As saga is sort of a state machine I'm not sure how `combineLatest`  should work - at least looking at your written test. The same thing can be achieved with just `yield all([take(a), take(b)])`, cant it?

I think `combineLatest` should work more like `takeEvery` - so like this:
```js
function* saga([action_a, action_b]) {
  // do smth
}
const task = yield combineLatest([type_a, type_b], saga)
```

WDYT?

**Comment by Andarist** [comment]
> The difference would be that combineLatest would always use the latest take, while your example would resolve with the first instance of each action that was taken.

Sure, but using it like this:
```js
const [action_a, action_b] = yield combineLatest([type_a, type_b])
```
is not suitable for generators (as they are stateful functions) - cannot inject back new values after we resolve it (`combineLatest`) for the first time.

With `race` the story is different because it alone has no long-lived state, it just resolves and doesnt have to remember prior invocations. While `combineLatest` would have to remember previous invocations and there is no way to glue them together (if you want to use it like in your example), because there is no way to judge if the received effect is the same one that was received before (ofc we could try some caching per saga, but this would overcomplicate things **a lot**)

**Comment by NeoLegends** [comment]
I‘m not sure whether I understand you correctly? Remember the original issue? I think you were talking about the same there until I made myself more clear?

CombineLatest would not have any long-lived-state and would not hae to remember previous invocations. It would resolve only when it has seen an action of all types, discarding duplicate ones.

**Comment by NeoLegends** [comment]
Currently on mobile but combineLatest is supposed to work like: block the saga until you have collected at least one action of every specified type. If you see multiple ones of one type while still waiting for others, replace the previously saved action of that type with the new one.

**Comment by Andarist** [comment]
> I‘m not sure whether I understand you correctly? Remember the original issue? I think you were talking about the same there until I made myself more clear?

I've remembered the issue, just not exact discussion around it. Thanks for clarifying.

Unfortunately I cannot merge this at the moment (until we figure out custom effects), desired effect can be expressed easily as a composition of other effects - just like `takeEvery`, `takeLatest` & `throttle`.

Having it as a built-in effect (handled by `proc`) would prevent removing it from production bundles for people who are not interested in it.

I'd gladly accept version based on `fsmIterator` though.

**Comment by NeoLegends** [comment]
> Unfortunately I cannot merge this at the moment (until we figure out custom effects), desired effect can be expressed easily as a composition of other effects - just like takeEvery, takeLatest & throttle.

You're right, but the ergonomics benefits of this are real. `takeEvery`, `takeLatest`,  and `throttle` are all effects that fire multiple times. This justifies they take a second saga to fork when they resolve, since that function will be called potentially lots of times. `combineLatest` would only resolve once. Thereby a version based on `fsmIterator` has severely crippled readability, because the forked saga would only run once (per effect invocation). Such an implementation does not suffice, unfortunately.

**Comment by NeoLegends** [comment]
I see, seems like I cannot convince you yet. ;)

Wanna leave this open if you decide otherwise in the future?

**Comment by Andarist** [comment]
Sorry that you've put some effort to this PR already, but as stated - to keep the API small & focused I don't want to put more helpers in the core itself. 

I'm going to close this now, but feel free to add any comments if you'd like to.

**Pull request closed without merging**
