### PR TITLE
Fixed location of the delay function in the beginner tutorial

### PR DESCRIPTION
**Pull request by IvanJov**
Hi! I found one small issue in the beginner tutorial, this PR fixes it. Thanks!

### CODE REVIEW

**Comment by Andarist** [comment]
Actually this is correct for v1-beta .

**Comment by IvanJov** [comment]
@Andarist Hmm, okay. So on this line https://github.com/redux-saga/redux-saga/pull/1402/files#diff-91df1104cefdb22cf3dc49af49294dd9L282, there was already an import directly from `redux-saga`. Should I change it everywhere to `redux-saga/utils`?

**Comment by restrry** [comment]
as @Andarist [noticed](https://github.com/redux-saga/redux-saga/pull/1401#issuecomment-381434597) we have 2 different `delay` functions across code base & documentations. 
imho, `delay` from effects is part of api, `delay` from utils is internal thing. So probably that tutorial should be changed to use another function that returns a promise, since the whole tutorial explains how redux-saga can handle both effects and promises

**Comment by IvanJov** [comment]
@restrry Okay, that makes sense. I am not sure I understand what do you mean with `that tutorial should be changed to use another function that returns a promise`?

**Comment by restrry** [comment]
@IvanJov for example, instead of importing delay from utils, we can define function
```
const delay = (ms) => new Promise (res => setTimeout(res, ms))
```
now referring to it, in context of the tutorial, makes sense.

**Comment by Andarist** [comment]
good idea @restrry , that way we wouldnt confuse ppl about having 2 `delay` functions

**Comment by IvanJov** [comment]
Gotcha, let me change that!

**Comment by IvanJov** [comment]
@Andarist @restrry Please check it again!

**Comment by restrry** [comment]
👍  from me

**Comment by Andarist** [comment]
Thanks!

**Pull request merged**
