### PR TITLE
Prepare for upgrading gitbook

### PR DESCRIPTION
**Pull request by shinima**
From #1469. Prepare for upgrading gitbook. A demo site could be view at https://shinima.gitbook.io/redux-saga/

Sadly, some in-page links in [api-reference](https://shinima.gitbook.io/redux-saga/table-of-contents/api-reference) are broken. In GitHub, `take(pattern​)` will be translated into `#takepattern`, but in GitBook it will be translated into `#take-pattern`. So I need to figure how to write in-page links that works both in GitHub and in GitBook.

### CODE REVIEW

**Comment by Andarist** [comment]
> So I need to figure how to write in-page links that works both in GitHub and in GitBook.

Maybe worth asking on GitBook's live chat or something? Seems like a popular problem.

**Comment by shinima** [comment]
Thank you to invite me to become a collaborator!
I am glad to help make redux-saga better. I will read the source code again and find what I could do. I am a master student from China, so I have plenty of free time until my graduation. My English is a bit poor, so sometimes I may not be able to explain logic/code/situations clearly. 😃

**Comment by Andarist** [comment]
> My English is a bit poor, so sometimes I may not be able to explain logic/code/situations clearly.

That's not a problem, I'm not a native english speaker either 😉 You can always reach out to me on gitter to have a talk about the codebase etc

**Comment by shinima** [comment]
I've reported this issue to the GitBook's  [here](https://gitbook.canny.io/bugs/p/github-and-gitbook-treat-the-parenthesis-in-anchor-differently).

The same problems appear in redux docs too. It seems that we may wait some time before gitbook fixing this issue.

**Comment by shinima** [comment]
It seems that gitbook won't fix the inconsistency in the near future, so I'm closing this issue.

**Pull request closed without merging**
