### PR TITLE
Issue #1063 - add test for using takeLatest on an actionChannel

### PR DESCRIPTION
**Pull request by erikvold**

### CODE REVIEW

**Comment by Andarist** [comment]
Oh, I see what u meant! I think `buffers.sliding(1)` is exactly what you need. :)

**Comment by erikvold** [comment]
> Oh, I see what u meant! I think buffers.sliding(1) is exactly what you need. :)

after looking in to it some more that, `buffers.dropping(1)` looks like what I want (I just need to know if there was a new action buffered), but now when I use it, my tests fail when I compare:

    assert.deepEqual(gen.next().value, actionChannel(TYPE, buffers.dropping(1)));

When I log the two values I get this:

```
{ '@@redux-saga/IO': true,
  ACTION_CHANNEL: 
   { pattern: 'TYPE',
     buffer: 
      { isEmpty: [Function: isEmpty],
        put: [Function: put],
        take: [Function: take],
        flush: [Function: flush] } } }
{ '@@redux-saga/IO': true,
  ACTION_CHANNEL: 
   { pattern: 'TYPE',
     buffer: 
      { isEmpty: [Function: isEmpty],
        put: [Function: put],
        take: [Function: take],
        flush: [Function: flush] } } }
```

So I guess that the functions are being compared and they are not equal.

**Comment by erikvold** [comment]
@Andarist I recreated my test in #1085 to show what is failing.

**Comment by Andarist** [comment]
Going to close this one as it seems not relevant anymore, please ping me here if you feel it needs reopening though.

**Pull request closed without merging**
